### ISSUE TITLE
minimal documentation and information

### ISSUE THREAD

**Issue by mckaygerhard** [hardinfo2/server#1]
For those who don't know... hardinfo2/hardinfo sends data (if the user wishes/command) to a server, this is used to have better knowledge of the hardware present, and thus improve technical support as well as the support of the Linux system, making this data shareable

Of course **we need to put a document that show specification** into the repository.. **so developers can interact and make improvements..** this is a important issue cos currently there is no documentation to complete issue https://github.com/hardinfo2/hardinfo2/issues/4

**Comment by hwspeedy** [comment]
@diazvictor

I have started the doc process of API and database and added these docs to the server repo:
https://github.com/hardinfo2/server

The missing JSON<->Mariadb has been implemented. It is now clean LAMP.
